"""empty message

Revision ID: 848a6f5a8378
Revises: 
Create Date: 2025-03-02 20:52:11.663484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848a6f5a8378'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('preview_text', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=True),
    sa.Column('is_viewed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('task',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('site_link', sa.String(length=200), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_post_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('post_info',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('author_link', sa.String(length=200), nullable=True),
    sa.Column('author_name', sa.String(length=200), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('count_reactions', sa.Integer(), nullable=True),
    sa.Column('uuid_post', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['uuid_post'], ['post.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('comment',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('author_link', sa.String(length=200), nullable=True),
    sa.Column('author_name', sa.String(length=200), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('uuid_post_info', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['uuid_post_info'], ['post_info.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('post_info')
    op.drop_table('task')
    op.drop_table('post')
    # ### end Alembic commands ###
